---

- apt: name=apache2 state=latest
  name: Install on Debian
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    
- yum: name=httpd state=latest
  name: Install on Redhat
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
 